export enum GAME_NAME_ENUMS {
  OVERWATCH = 1,
  FORTNITE = 2,
  MODERN_WARFARE_2 = 3,
  AVATAR_FRONTIERS_OF_PANDORA = 4,
  CALL_OF_DUTY = 5,
  VALORANT = 6,
  LEAGUE_OF_LEGENDS = 7,
  COUNTER_STRIKE_2 = 8,
  APEX_LEGENDS = 9,
  ROCKET_LEAGUE = 10
}

export const GAME_NAME_DESCRIPTIONS: Record<GAME_NAME_ENUMS, string> = {
  [GAME_NAME_ENUMS.OVERWATCH]: 'Overwatch',
  [GAME_NAME_ENUMS.FORTNITE]: 'Fortnite',
  [GAME_NAME_ENUMS.MODERN_WARFARE_2]: 'Modern Warfare 2',
  [GAME_NAME_ENUMS.AVATAR_FRONTIERS_OF_PANDORA]: 'Avatar: Frontiers of Pandora',
  [GAME_NAME_ENUMS.CALL_OF_DUTY]: 'Call of Duty',
  [GAME_NAME_ENUMS.VALORANT]: 'Valorant',
  [GAME_NAME_ENUMS.LEAGUE_OF_LEGENDS]: 'League of Legends',
  [GAME_NAME_ENUMS.COUNTER_STRIKE_2]: 'Counter-Strike 2',
  [GAME_NAME_ENUMS.APEX_LEGENDS]: 'Apex Legends',
  [GAME_NAME_ENUMS.ROCKET_LEAGUE]: 'Rocket League'
};
